version: "3"
services:
  db:
    image: postgres:13.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    stdin_open: true
    tty: true
