version: "3"
services:
  postgres:
    image: postgres:13.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    stdin_open: true
    tty: true
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/postgres -schemas=flyway -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ./flyway/sql:/flyway/sql
    depends_on:
      - postgres
